language: php # language 

php:
- 7.4

services:
- mysql # will init MySQL 

before_script:
- cp .env.travis .env # copying .env.travis 
- mysql -e 'CREATE DATABASE test_db;'
- composer self-update
- composer install --no-interaction
- composer update
- php artisan key:generate
- php artisan migrate

script:
    - vendor/bin/phpunit # run PHPUnit